---
### tasks file for main
- name: Include all-in-one.yml
  include_tasks: all-in-one.yml

- name: Include pre.yml
  include_tasks: pre.yml

- name: Include images/image.yml
  include_tasks: images/image.yml

- name: Include app.yml
  include_tasks: app.yml

- name: Include harbor.yml
  include_tasks: harbor.yml

- name: Include nfs.yaml
  include_tasks: nfs.yaml

- name: Include n9e.yaml
  include_tasks: n9e.yaml

- name: Include rancher-monitor.yaml
  include_tasks: rancher-monitor.yaml

- name: Include metacontroller.yaml
  include_tasks: metacontroller.yaml

- name: Include gpu.yaml
  include_tasks: gpu.yaml

- name: Include extra.yaml
  include_tasks: extra.yaml

- name: Include clear.yaml
  include_tasks: clear.yaml


