###  import images tars
- name: create all tar
  file:
    path: "{{ tar_home }}"
    state: directory
    recurse: yes

- name: create monitor tar
  file:
    path: "{{ tar_home }}/monitor"
    state: directory
    recurse: yes



